# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'speck_weg\ui\dialog_training_program.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_training_program(object):
    def setupUi(self, Dialog_training_program):
        Dialog_training_program.setObjectName("Dialog_training_program")
        Dialog_training_program.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog_training_program.resize(427, 264)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_training_program)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(Dialog_training_program)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(Dialog_training_program)
        self.lineEdit_name.setText("")
        self.lineEdit_name.setMaxLength(32767)
        self.lineEdit_name.setClearButtonEnabled(True)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        self.label_description = QtWidgets.QLabel(Dialog_training_program)
        self.label_description.setObjectName("label_description")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_description)
        self.textEdit_description = QtWidgets.QTextEdit(Dialog_training_program)
        self.textEdit_description.setMaximumSize(QtCore.QSize(16777215, 60))
        self.textEdit_description.setTabChangesFocus(True)
        self.textEdit_description.setObjectName("textEdit_description")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_description)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_save = QtWidgets.QPushButton(Dialog_training_program)
        self.pushButton_save.setDefault(True)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.pushButton_close = QtWidgets.QPushButton(Dialog_training_program)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_name.setBuddy(self.lineEdit_name)
        self.label_description.setBuddy(self.textEdit_description)

        self.retranslateUi(Dialog_training_program)
        self.pushButton_close.clicked.connect(Dialog_training_program.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_training_program)

    def retranslateUi(self, Dialog_training_program):
        _translate = QtCore.QCoreApplication.translate
        Dialog_training_program.setWindowTitle(_translate("Dialog_training_program", "Programm"))
        self.label_name.setText(_translate("Dialog_training_program", "&Name"))
        self.lineEdit_name.setPlaceholderText(_translate("Dialog_training_program", "Neues Programm"))
        self.label_description.setText(_translate("Dialog_training_program", "&Beschreibung"))
        self.textEdit_description.setPlaceholderText(_translate("Dialog_training_program", "Optionale Beschreibung"))
        self.pushButton_save.setText(_translate("Dialog_training_program", "&Speichern"))
        self.pushButton_close.setText(_translate("Dialog_training_program", "S&chliessen"))
from . import resources_rc
